### PR TITLE
Adds newrelic-server setup and newrelic deployment call

### PR DESCRIPTION
**Pull request by zalphi**
Basic blueprint to setup New Relic server.

Notify deployments expects you to use a Git Tag for each deployment and builds a changelog between those tags.

### CODE REVIEW

**Comment by hannseman** [comment]
I don't really like the idea of adding a dependency for `requests` just for this request.post. What do you think of using `urllib` instead?

**Comment by hannseman** [comment]
We should not use private API:s bundled by pip for making http-requests. `urllib2` should be enough.

```
import urllib2
import urllib
request = urllib2.Request("http://www.example.com", headers=headers)
request_payload = urllib.urlencode(payload)
urllib2.urlopen(request, data=request_payload)
```

**Comment by zalphi** [comment]
Pip private API was a longshot. 

Fixed now. Tested and works. Changelog got some minor characters that newrelics not happy about

```
[33m3859d384eb681f6b1236f91d0fd0b5e8bd097710[m dont update product dimension
```

**Comment by hannseman** [comment]
Looking good!

**Pull request merged**
