### PR TITLE
added support for excluding table data in postgres blueprint

### PR DESCRIPTION
**Pull request by jocke-l**

### CODE REVIEW

**Comment by lundberg** [comment]
I don't think the blueprint setting need to align with pg_dump option naming.
Rename settings to:
``` yaml
dump:
  exclude_tables:
    - foo
    - bar
```

**Comment by jocke-l** [comment]
pg_dump's `--exclude-table-data` doesn't exclude the table itself, but it's data. So it would be confusing to have the option named `exclude_tables`. As for the `dump_options` -> `dump`, I totally agree.

**Comment by andreif** [comment]
@jocke-l Could you resolve conflict and maybe squash the commits?

**Comment by andreif** [comment]
I'll create a new PR.

**Pull request closed without merging**
