### PR TITLE
Add blueprint to generate .env file

### PR DESCRIPTION
**Pull request by andreif**
TODO:

 - [x] Custom variables in blueprint settings?
 - [x] Check if `.env` location is fine
 - [x] It's not! Change it to `~/.profile`
 - [ ] It does not fit well, try `~/.pam_environment`
 - [ ] Check if application part can do it so we don't need extra blueprint

### CODE REVIEW

**Comment by andreif** [comment]
@lundberg What do you think?

**Comment by hannseman** [comment]
Maybe use the standard `~/.profile` instead of `.env`?

**Comment by andreif** [comment]
@hannseman `.env` seems quite popular https://www.google.se/search?hl=en-US&q=dotenv

**Comment by hannseman** [comment]
How will the variables in `.env` file be loaded? `~/.profile` and `~/.pam_environment` are automatically loaded on login.

**Comment by andreif** [comment]
Not sure if it's good to have one thing for all parts and always defined. But true, it reduces the need to source it. We can have `.env` for each part of server if needed. On the other hand one can have separate user for each part. Hard to decide :smile:

**Comment by andreif** [comment]
Well, since we don't have an example of multi-part system which would need several env files, I will change to `~/.profile`

**Comment by lundberg** [comment]
If the need for this is when ssh:ing to the server and need the proper configured shell env, then it's possible to achieve the similar by using arbitrary commands `fab -E live -R app -- bash`.

I'm experimenting on a built-in refabric ssh task that will do this, not quite completed, but kind of working.

**Comment by andreif** [comment]
I think it's still good to have a place to have all env vars on the server, in case someone will ssh to a server an usual way.

**Comment by andreif** [comment]
@hannseman Well, you are right, pam env seems much better place for such things

**Comment by andreif** [comment]
Rebased, renamed, force-pushed

**Comment by andreif** [comment]
I am looking into incorporating it into `application`, so it happens automatically. Let me know if you feel bad about it!

**Pull request merged**
