### PR TITLE
rabbitmq: Don't fail to configure if no cookie exists

### PR DESCRIPTION
**Pull request by kyrias**

### CODE REVIEW

**Comment by andreif** [comment]
Can one use `or` there?

**Comment by andreif** [comment]
Oh, no, sorry

**Comment by kyrias** [comment]
Well, we could actually have a second variable and use an or in the original if.

**Comment by andreif** [comment]
What about making a tuple of the two and then use it in `any`

**Comment by kyrias** [comment]
That's a good idea

**Comment by andreif** [comment]
```py
uploads = (
  blueprint.upload('rabbitmq/', '/etc/rabbitmq/'),
  blueprint.upload('erlang.cookie', '/var/lib/rabbitmq/.erlang.cookie', user='rabbitmq'),
)
if any(uploads): ...
```

**Comment by kyrias** [comment]
Done!

**Pull request merged**
