### PR TITLE
ruby.py legacy support for gem install -v flags

### PR DESCRIPTION
**Pull request by henriklindgren**
This will allow you to use the following combinations, allowing for legacy -v flag where single rows must be used for each install command:
```
ruby:
    gems:
        - sass -v 3.4.21
        - compass -v 1.0.3

ruby:
    gems:
        - sass:3.4.21
        - compass:1.0.3

ruby:
    gems:
        - sass:3.4.21 compass:1.0.3

ruby:
    gems:
        - sass compass

ruby:
    gems:
        - sass
        - compass
```

### CODE REVIEW

**Comment by zalphi** [comment]
@hannseman kan du kika på denna?

**Comment by zalphi** [comment]
this PR contains cherry-picked commits from https://github.com/5monkeys/blues/pull/82

**Comment by henriklindgren** [comment]
@hannseman wanted me to check if there is a way to not start an SSH connection per loop of the ruby gem installer, so wait with merge.

**Comment by henriklindgren** [comment]
@hannseman @zalphi fixed and tested, I haven't look through the cherry picked commits, but the ruby ssh thing is fixed

**Comment by hannseman** [comment]
Looking good!

**Pull request merged**
